Homework2
saryan02/fefu-ios-base-repo pull request #1
Opened 2021-10-30 03:25 UTC by saryan02

Во втором идз в основном всё сделано, но не работает переход по ячейке на другой ViewController. Должно работать, но что-то не работает.
1идз переделано, теперь все констранты синие

2021-11-03 08:03 UTC, fplsv requested changes

2021-11-03 08:03 UTC, fplsv commented on fefuactivity/ListlViewController.swift
> +//    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
`didSelectRowAt` - это метод UITableViewDelegate, а не датасурса, поэтому и не работает
Второй момент - у тебя Segue стоит Show, а надо Push. Когда в дизайне видно "< назад", то это 99% push, а не present (== show)

2021-11-03 08:03 UTC, fplsv commented on cells/TableViewCell.swift
> +        contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10))
так лучше не делать, но оставь как есть. 

ContentView используется системой под капотом и менять его фрейм не самая лучшая практика. Там в дизе есть справа ячейка и можно ее иерархию посмотреть, будет видно как должно быть

2021-11-03 08:03 UTC, fplsv approved these changes

2021-11-03 08:03 UTC, fplsv commented
Оценка - 7

2021-11-04 05:06 UTC, saryan02 commented
Я сделал переход по ячейке, там опечатка была, perfromSegue было написано, а не performSegue.
Цвет ячейки по figme, добавлены секции. В первом идз прозрачный header.
Проверти, пожалуйста

2021-11-15 06:27 UTC, fplsv commented
Оценка - 9

2021-11-15 06:27 UTC, merged